# Generated by Django 5.0.3 on 2024-04-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("sub_title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("background_image", models.ImageField(upload_to="baner")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
