# Generated by Django 5.0.3 on 2024-04-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="description",
        ),
        migrations.AddField(
            model_name="services",
            name="small_description",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="services",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
