# Generated by Django 5.0.3 on 2024-04-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_services_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="small_description",
        ),
        migrations.AddField(
            model_name="services",
            name="description",
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
