# Generated by Django 5.0.3 on 2024-04-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_remove_services_small_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientLogos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("background_image", models.ImageField(upload_to="baner")),
            ],
        ),
        migrations.RenameModel(
            old_name="Baner",
            new_name="Banner",
        ),
    ]
