# Generated by Django 5.0.3 on 2024-04-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_clientlogos_rename_baner_banner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientlogos",
            old_name="background_image",
            new_name="image",
        ),
    ]
