# Generated by Django 5.0.3 on 2024-04-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_rename_background_image_clientlogos_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientlogos",
            name="image",
        ),
        migrations.AddField(
            model_name="clientlogos",
            name="logo",
            field=models.ImageField(default=1, upload_to="logos/"),
            preserve_default=False,
        ),
    ]
