# Generated by Django 5.0.3 on 2024-04-05 09:15

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_remove_clientlogos_image_clientlogos_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="baner/")),
                ("description", tinymce.models.HTMLField()),
                (
                    "services",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.services"
                    ),
                ),
            ],
        ),
    ]
