# Generated by Django 5.0.3 on 2024-04-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_servicedescription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicedescription",
            old_name="description",
            new_name="service_description",
        ),
    ]
