# Generated by Django 5.0.3 on 2024-04-05 09:20

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_rename_description_servicedescription_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedescription",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="baner/"),
        ),
        migrations.AlterField(
            model_name="servicedescription",
            name="service_description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
