# Generated by Django 5.0.3 on 2024-04-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_remove_blog_sub_title_remove_services_sub_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="background_image",
        ),
        migrations.AddField(
            model_name="blog",
            name="img",
            field=models.ImageField(default=1, upload_to="blog/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="thumbnail_img",
            field=models.ImageField(default=1, upload_to="blog/"),
            preserve_default=False,
        ),
    ]
