# Generated by Django 5.0 on 2024-04-08 05:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0015_testimonial_alter_banner_sub_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="services",
            old_name="background_image",
            new_name="image",
        ),
    ]
