# Generated by Django 5.0 on 2024-04-08 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0016_rename_background_image_services_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientlogos",
            options={
                "verbose_name": "Client Logo",
                "verbose_name_plural": "Client Logos",
            },
        ),
    ]
